[project]
name = "psof"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "mypy>=1.15.0",
    "uvicorn>=0.34.0",
]
