"""Creating first tables

Revision ID: 075f27cc5cdd
Revises:
Create Date: 2025-04-07 22:01:00.296882

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "075f27cc5cdd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), nullable=True, server_default=sa.func.now()
        ),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("short_description", sa.String(), nullable=True),
        sa.Column("long_bio", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name="username_unique "),
    )
    op.create_table(
        "liked_post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), nullable=True, server_default=sa.func.now()
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "post_id", name="user_post_unique"),
    )
    op.create_index("liked_post_user_idx", "liked_post", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("liked _post_user_idx", table_name="liked_post")
    op.drop_table("liked_post")
    op.drop_table("user")
    # ### end Alembic commands ###
